import {
  ArrowRight,
  Bell,
  BookOpen,
  Briefcase,
  Calculator,
  CalendarSync,
  Camera,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  CloudSun,
  Coins,
  FileCheck2,
  FolderLock,
  Globe,
  GraduationCap,
  Grid3x3,
  Handshake,
  Info,
  Landmark,
  LayoutDashboard,
  Leaf,
  Map,
  Menu,
  Network,
  Plug,
  QrCode,
  Scale,
  Search,
  ShieldAlert,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Sprout,
  Store,
  Tag,
  Thermometer,
  ThermometerSnowflake,
  Timer,
  TriangleAlert,
  Truck,
  Users,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const registry: Record<string, LucideIcon> = {
  "arrow-right": ArrowRight,
  bell: Bell,
  "book-open": BookOpen,
  briefcase: Briefcase,
  calculator: Calculator,
  "calendar-sync": CalendarSync,
  camera: Camera,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clock: Clock,
  "cloud-sun": CloudSun,
  coins: Coins,
  "file-check-2": FileCheck2,
  "folder-lock": FolderLock,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "grid-3x3": Grid3x3,
  handshake: Handshake,
  info: Info,
  landmark: Landmark,
  "layout-dashboard": LayoutDashboard,
  leaf: Leaf,
  map: Map,
  menu: Menu,
  network: Network,
  plug: Plug,
  "qr-code": QrCode,
  scale: Scale,
  search: Search,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sprout: Sprout,
  store: Store,
  tag: Tag,
  thermometer: Thermometer,
  "thermometer-snowflake": ThermometerSnowflake,
  timer: Timer,
  "triangle-alert": TriangleAlert,
  truck: Truck,
  users: Users,
};

export function Icon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Cmp = registry[name] ?? Sprout;
  return <Cmp className={cn("h-5 w-5 shrink-0", className)} aria-hidden="true" />;
}
